apiVersion: v1
name: openrmf
version: 1.1.0
description: The OpenRMF web application to manage DoD STIGs and NIST Risk Management Framework Compliance
keywords:
  - RMF
  - openrmf
  - risk management framework
maintainers:
  - name: Dale Bingham
    email: dale.bingham@cingulara.com
  - name: David Gould
    email: dgould@tutelasec.com
engine: gotpl 
appVersion: 0.9
deprecated: false