apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openrmf-compliance-ingress
  namespace: openrmf
  labels:
    app: openrmf
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: Compliance API Ingress
    release: {{ .Release.Name }}
    revision: "{{ .Release.Revision }}"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, OPTIONS"
spec:
  rules:
  - host: {{.Values.dnsName}}
    http:
      paths:
      - path: /compliance(/|$)(.*)
        backend:
          serviceName: openrmf-compliance
          servicePort: 8080