apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-msg-compliance
  namespace: openrmf
  labels:
    app: openrmf
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: compliance-nats-message-client
    release: {{ .Release.Name }}
    revision: "{{ .Release.Revision }}"
spec:
  selector:
    matchLabels:
      run: openrmf-msg-compliance
  replicas: 1
  template:
    metadata:
      labels:
        run: openrmf-msg-compliance
    spec:
      containers:
      - name: openrmf-msg-compliance
        image: cingulara/openrmf-msg-compliance:0.8
        ports:
        - containerPort: 8080
        env:
        - name: NATSSERVERURL
          value: nats://natsserver:4222
        resources:
          limits:
            memory: "1Gi"
            cpu: "250m"
          requests:
            memory: "500M"
            cpu: "100m"