apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openrmf-save-ingress
  namespace: openrmf
  labels:
    app: openrmf
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: save-api-ingress
    release: {{ .Release.Name }}
    revision: "{{ .Release.Revision }}"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
spec:
  rules:
  - host: {{.Values.dnsName}}
    http:
      paths:
      - path: /save(/|$)(.*)
        backend:
          serviceName: openrmf-save
          servicePort: 8080