apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-scoredb
  namespace: openrmf
  labels:
    app: openrmf
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: score-mongodb
    release: {{ .Release.Name }}
    revision: "{{ .Release.Revision }}"
spec:
  selector:
    matchLabels:
      run: openrmf-scoredb
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        run: openrmf-scoredb
    spec:
      containers:
      - name: openrmf-scoredb
        image: cingulara/openrmf-scoredb:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: myp2ssw0rd
        - name: MONGO_INITDB_DATABASE
          value: openrmfscore
        resources:
          requests:
            memory: "500M"
            cpu: "250m"
        volumeMounts:
        - mountPath: /data/db
          name: mongodata-scoredb
      restartPolicy: Always
      volumes:
      - name: mongodata-scoredb
        persistentVolumeClaim:
          claimName: openrmf-scoredb-claim
---
apiVersion: v1
kind: Service
metadata:
  name: openrmf-scoredb
  namespace: openrmf
spec:
  ports:
  - name: mongodb-scoredb
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    run: openrmf-scoredb
  sessionAffinity: None
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: openrmf
  name: openrmf-scoredb-claim
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi