version : '3'
 
services:
### 1 Web Front End Container
  openrmf-web:
    image: cingulara/openrmf-web
    ports:
      - 8080:80
    depends_on:
      - openrmfapi-scoring
      - openrmfapi-save
      - openrmfapi-template
      - openrmfapi-upload
      - openrmfapi-read
      - openrmfapi-compliance
    networks:
      - openrmf-dev

### 7 API Containers
  openrmfapi-scoring:
    image: cingulara/openrmf-api-scoring
    ports:
      - 8090:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - MONGODBCONNECTION=mongodb://openrmfscore:openrmf1234!@scoredb/openrmfscore?authSource=openrmfscore
      - MONGODB=openrmfscore
    depends_on:
      - scoredb
    networks:
      - openrmf-dev
  
  openrmfapi-save:
    image: cingulara/openrmf-api-save
    ports:
      - 8082:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - MONGODBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - MONGODB=openrmf
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - openrmfmsg-score
      - checklistdb
      - natsserver
    networks:
      - openrmf-dev

  openrmfapi-template:
    image: cingulara/openrmf-api-template
    ports:
      - 8088:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - MONGODBCONNECTION=mongodb://openrmftemplate:openrmf1234!@templatedb/openrmftemplate?authSource=openrmftemplate
      - MONGODB=openrmftemplate
    depends_on:
      - templatedb
    networks:
      - openrmf-dev

  openrmfapi-upload:
    image: cingulara/openrmf-api-upload
    ports:
      - 8086:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - MONGODBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - MONGODB=openrmf
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - openrmfmsg-score
      - checklistdb
      - natsserver
    networks:
      - openrmf-dev

  openrmfapi-read:
    image: cingulara/openrmf-api-read
    ports:
      - 8084:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - MONGODBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - MONGODB=openrmf
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - checklistdb
    networks:
      - openrmf-dev

  openrmfapi-compliance:
    image: cingulara/openrmf-api-compliance
    ports:
      - 8092:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - NATSSERVERURL=nats://natsserver:4222
    networks:
      - openrmf-dev

  openrmfapi-controls:
    image: cingulara/openrmf-api-controls
    ports:
      - 8094:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - NATSSERVERURL=nats://natsserver:4222
    networks:
      - openrmf-dev

  openrmfapi-audit:
    image: cingulara/openrmf-api-audit
    ports:
      - 8094:8080
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://*:8080
      - MONGODBCONNECTION=mongodb://openrmfaudit:openrmf1234!@auditdb/openrmfaudit?authSource=openrmfaudit
      - MONGODB=openrmfaudit
      - NATSSERVERURL=nats://natsserver:4222
    networks:
      - openrmf-dev

### 7 Messaging Containers
  openrmfmsg-score:
    image: cingulara/openrmf-msg-score
    environment:
      - MONGODBCONNECTION=mongodb://openrmfscore:openrmf1234!@scoredb/openrmfscore?authSource=openrmfscore
      - MONGODB=openrmfscore
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - scoredb
      - natsserver
    networks:
      - openrmf-dev

  openrmfmsg-checklist:
    image: cingulara/openrmf-msg-checklist
    environment:
      - MONGODBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - MONGODB=openrmf
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - checklistdb
      - natsserver
    networks:
      - openrmf-dev

  openrmfmsg-compliance:
    image: cingulara/openrmf-msg-compliance
    environment:
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - natsserver
    networks:
      - openrmf-dev

  openrmfmsg-controls:
    image: cingulara/openrmf-msg-controls
    environment:
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - natsserver
    networks:
      - openrmf-dev

  openrmfmsg-template:
    image: cingulara/openrmf-msg-template
    environment:
      - MONGODBCONNECTION=mongodb://openrmftemplate:openrmf1234!@templatedb/openrmftemplate?authSource=openrmftemplate
      - MONGODB=openrmftemplate
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - templatedb
      - natsserver
    networks:
      - openrmf-dev

  openrmfmsg-system:
    image: cingulara/openrmf-msg-system
    environment:
      - MONGODBCONNECTION=mongodb://openrmf:openrmf1234!@checklistdb/openrmf?authSource=openrmf
      - MONGODB=openrmf
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - checklistdb
      - natsserver
    networks:
      - openrmf-dev

  openrmfmsg-audit:
    image: cingulara/openrmf-msg-audit
    environment:
      - MONGODBCONNECTION=mongodb://openrmfaudit:openrmf1234!@auditdb/openrmfaudit?authSource=openrmfaudit
      - MONGODB=openrmfaudit
      - NATSSERVERURL=nats://natsserver:4222
    depends_on:
      - checklistdb
      - natsserver
    networks:
      - openrmf-dev

### 4 MongoDB Containers
  checklistdb:
    image: mongo:4.0.5
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmf
    volumes:
      - checklist-dev-data-volume:/data/db
      - ../initializeChecklist.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - openrmf-dev

  scoredb:
    image: mongo:4.0.5
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmfscore
    volumes:
      - score-dev-data-volume:/data/db
      - ../initializeScore.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - openrmf-dev

  templatedb:
    image: mongo:4.0.5
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmftemplate
    volumes:
      - template-dev-data-volume:/data/db
      - ../initializeTemplate.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - openrmf-dev

  auditdb:
    image: mongo:4.0.5
    restart: always
    ports:
      - 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=myp2ssw0rd
      - MONGO_INITDB_DATABASE=openrmfaudit
    volumes:
      - audit-data-volume:/data/db
      - ../initializeAudit.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - openrmf-dev

### NATS messaging container (internal)
  natsserver: 
    image: nats:2.1.2-linux
    restart: always
    ports:
      - 4222
      - 6222
      - 8222
    networks:
      - openrmf-dev

### Metrics
  natspromexporter: 
    image: synadia/prometheus-nats-exporter:latest
    command: -DV -varz http://nats:8222
    restart: always
    ports:
      - 7777
    networks:
      - openrmf-dev

  prometheus:
    image: prom/prometheus
    restart: always
    ports:
      - 9090
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - openrmf-dev

  grafana: 
    image: grafana/grafana
    #command:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=1qaz2WSX3edc4RFVgr@fana
    restart: always
    ports:
      - 3000:3000
    networks:
      - openrmf-dev

### put all the volume listings here for persistent data
volumes:
  template-dev-data-volume:
  checklist-dev-data-volume:
  score-dev-data-volume:
  audit-data-volume:

### put all the networks here
networks:
  openrmf-dev: