apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-compliance
  namespace: openrmf
  labels:
    app: openrmf
    component: api-compliance
spec:
  selector:
    matchLabels:
      run: openrmf-compliance
  replicas: 2
  template:
    metadata:
      labels:
        run: openrmf-compliance
    spec:
      containers:
      - name: openrmf-compliance
        image: cingulara/openrmf-api-compliance:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: ASPNETCORE_URLS
          value: http://*:8080
        - name: openrmf-api-read-server
          value: http://openrmfapi-read:8080
        - name: openrmf-api-controls-server
          value: http://openrmfapi-controls:8080
        resources:
          limits:
            memory: "1Gi"
            cpu: "750m"
          requests:
            memory: "500M"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: openrmf-compliance
  namespace: openrmf
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: openrmf-compliance
  sessionAffinity: None
  type: NodePort
