apiVersion: apps/v1
kind: Deployment
metadata:
  name: openrmf-msg-score
  namespace: openrmf
  labels:
    app: openrmf
    component: msg-score
spec:
  selector:
    matchLabels:
      run: openrmf-msg-score
  replicas: 2
  template:
    metadata:
      labels:
        run: openrmf-msg-score
    spec:
      containers:
      - name: openrmf-msg-score
        image: cingulara/openrmf-msg-score:latest
        ports:
        - containerPort: 8080
        env:
        - name: openrmf-api-read-server
          value: http://openrmfapi-read:8080
        - name: natsserverurl
          value: nats://natsserver:4222
        - name: mongoConnection
          value: mongodb://openrmfscore:openrmf1234!@openrmf-scoredb/openrmfscore?authSource=openrmfscore
        - name: mongodb
          value: openrmfscore
        resources:
          limits:
            memory: "1Gi"
            cpu: "750m"
          requests:
            memory: "500M"
            cpu: "250m"