apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: openrmf-template-ingress
  namespace: openrmf
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: template.openrmf
    http:
      paths:
      - path: /
        backend:
          serviceName: openrmf-template
          servicePort: 8080